Use 'Admin approval' setting for uploads
JoomGalleryfriends/JG4-dev pull request #121
Opened 2023-07-28 18:15 UTC by MrMusic

Actual result:
So far all uploaded images are automatically not approved.

Changes:
Move and activate the option 'Admin approval' to the configuration tab 'General Settings -> Uploads'. 
Modification of the language string.
Consider the setting for the uploads.

Expected result:
Depending on the setting in the configuration, the images are automatically approved or not when uploaded.

2023-08-01 07:34 UTC, MrMusic commented
Thank you for testing.

>PS: Multiple Upload is not working here.

That is correct, as this is contained in a separate[ pull request](https://github.com/JoomGalleryfriends/JG4-dev/pull/119). Unfortunately, this has not been merged yet. 
Since the change only affects a single line, you can make the change yourself if necessary.

2023-08-01 10:32 UTC, Elfangor93 requested changes

2023-08-01 10:32 UTC, Elfangor93 commented on administrator/com_joomgallery/src/Service/Uploader/Uploader.php
> +    // Image approved by default
I would rather add this lines to the ImageTable::bind() method.
(Joomgallery\Component\Joomgallery\Administrator\Table\ImageTable).
When in the ImageTable the configuration `jg_approve` will be considered everytime an image gets created. When in the uploader service it is considered only when adding an image using the uploader service.

2023-08-01 10:32 UTC, Elfangor93 commented on administrator/com_joomgallery/forms/config.xml
> +        <field name="jg_approve"
If you add a new configuration setting you also have to add the corresponding column into the database table (#__joomgallery_configs). Otherwise the setting will not be saved.

2023-08-11 09:38 UTC, MrMusic commented on administrator/com_joomgallery/src/Service/Uploader/Uploader.php
> +    // Image approved by default
Should be fixed now.

2023-08-12 07:23 UTC, rowi68 commented
Hello everyone,
just finished my first test... :-)

So it works for me on a subdomain...,
![cycling](https://github.com/JoomGalleryfriends/JG4-dev/assets/142021647/02f4f6c7-f71d-410a-aba3-85aefbdb6264)

....but I can't save images local. I don't know, perhaps a configuration issue with Xampp? (I use Xampp first time)
![unsupported_image-filetyp](https://github.com/JoomGalleryfriends/JG4-dev/assets/142021647/f6073d18-8dca-4a21-a338-cc030ad0c7bb)

2023-08-12 08:15 UTC, AlexanderSupp commented
@rowi68 
....but I can't save images local. I don't know, perhaps a configuration issue with Xampp? (I use Xampp first time)

Please check in Joomla
Content, Media, Options, Allowed Extensions and Legal Image Extensions,
and also
JoomGallery, Configuration Sets, Supported image types
Maybe you use a jp**E**g-file and only jpg is defined.

2023-08-12 12:52 UTC, Elfangor93 requested changes

2023-08-12 12:52 UTC, Elfangor93 commented on administrator/com_joomgallery/src/Table/ImageTable.php
> +		$app  = Factory::getApplication()->bootComponent('com_joomgallery');
Please dont use the variable name `$app` for the JoomGallery extension object. Everywhere in Joomla `$app` is used to hold the CMSApplication object.
As a proposition, I am using `$component` in the code as the storage variable for the JoomGallery extension object.

2023-08-12 12:58 UTC, rowi68 commented
Hello Alex,

Thank you for advices. I could not find the reason. All file types like jpg,jpeg,png,gif,webp are defined and allowed, but non of them are storable. Because it works on my subdomain, I will continue testing there in future....

2023-08-12 14:40 UTC, MrMusic commented
>....but I can't save images local. I don't know, perhaps a configuration issue with Xampp? (I use Xampp first time)

@rowi68   thanks for testing.
If you are using Xampp for the first time, the GD extension is probably not activated. You have to activate it in php.ini.
Check which GD version is displayed in the JoomGallery configuration.

2023-08-12 14:54 UTC, MrMusic commented on administrator/com_joomgallery/src/Table/ImageTable.php
> +		$app  = Factory::getApplication()->bootComponent('com_joomgallery');
@Elfangor93 thanks for the assistance and explanation.
I hope it fits now.

2023-08-12 17:54 UTC, Elfangor93 approved these changes

2023-08-13 06:33 UTC, rowi68 commented
@MrMusic This was the cause. Now it works. Thanks for help....

2023-08-14 07:09 UTC, Elfangor93 commented
I tested this PR successfully. Tank you very much!

2023-08-14 07:09 UTC, merged