category view – css column grid & thumbnails
JoomGalleryfriends/JG4-dev pull request #137
Opened 2023-09-08 12:39 UTC by reilldesign

This pull request contains code and style sheets to display a responsive css column grid with thumbnails. The structure is similar to the Joomla core and cassiopeia files.

 .com-joomgallery-category is a bit long as a class name. Currently there is a mix of joom and jg prefixes. I would suggest to use jg- uniformly.

2023-09-09 06:09 UTC, Elfangor93 requested changes

2023-09-09 06:09 UTC, Elfangor93 commented on media/com_joomgallery/css/site.css
> +:root {
grey-300 is already defined in template.css from cassiopeia. Do we still need this declaration?

2023-09-09 06:09 UTC, Elfangor93 commented on media/com_joomgallery/css/site.css
> +.com-joomgallery-category.image {
This selector is empty...

2023-09-09 06:10 UTC, Elfangor93 commented
>.com-joomgallery-category is a bit long as a class name. Currently there is a mix of joom and jg prefixes. I would suggest to use jg- uniformly

Agree.

2023-09-09 06:39 UTC, eumel1602 commented
Hello. Thank you for your effort
It's also about displaying a category in FE?!
Attached is a picture of what it looks like on my test page. I don't know what your requirements are. Everything worked smoothly for me.
Since the image name is a link, the color of the font is "grey" and I would like a "bold" black letter better. I also find the title of the picture “in the middle” slightly better.

I don't know to what extent these PR settings are possible? I couldn't find anything ("square thumbnails", "access to image")
But that's probably not the point of PR.
![1](https://github.com/JoomGalleryfriends/JG4-dev/assets/96334985/fc04439d-efb5-458b-b221-7fa1eb962c29)

2023-09-10 06:40 UTC, Elfangor93 commented
Pull request closed since there is now a new one: See PR #138

2023-09-10 06:40 UTC, closed without merging