Update control panel
JoomGalleryfriends/JG4-dev pull request #149
Opened 2023-09-21 13:34 UTC by MrMusic

Changes:
Fixes for Joomla 5
Show available extensions (JG3)
Control Panel design changes

`$this->addMailTemplate` does not work in Joomla 5.
@Elfangor93 Do you have any suggestions for this?

2023-09-22 05:39 UTC, Elfangor93 requested changes

2023-09-22 05:39 UTC, Elfangor93 commented on administrator/com_joomgallery/src/View/Control/HtmlView.php
> +  $db = Factory::getContainer()->get('DatabaseDriver');
This would be the correct way of retrieving the db class.
$db = Factory::getContainer()->get(DatabaseInterface::class);

![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/c4973e0b-311b-447f-b2fa-16f858e01278)

2023-09-22 05:40 UTC, Elfangor93 commented
Here I listed the most important deprecations for Joomla 4:
http://wiki.tech.spuur.ch/joomla/framework/deprecations

2023-09-22 06:02 UTC, Elfangor93 commented
>$this->addMailTemplate does not work in Joomla 5.

I guess you refer to the addMailTemplate method in the script.php?
What exactly is the error message you get there? Because there is a Factory::getDbo(); in this method too. Maybe that's the problem?

2023-09-22 06:06 UTC, Elfangor93 requested changes

2023-09-22 06:06 UTC, Elfangor93 commented on script.php
> +/* auskommentiert wegen fehler in J5
I don't like the approach to comment out code. This way the error message disappears and we will forget about the issue still beeing existent.
I prefer having an error than commenting stuff out.

2023-09-22 09:41 UTC, MrMusic commented on administrator/com_joomgallery/src/View/Control/HtmlView.php
> +  $db = Factory::getContainer()->get('DatabaseDriver');
I had also already used this, but then followed the recommendations below:
https://forum.joomla.de/thread/19416-herstellen-einer-datenbankverbindung-innerhalb-eines-artikels-beitrags/?postID=140119#post140119
https://ghsvs.de/programmierer-schnipsel/joomla/334-jfactory-getdbo-ersatz-ab-joomla-4
Currently both solutions work

2023-09-22 09:42 UTC, MrMusic commented on script.php
> +/* auskommentiert wegen fehler in J5
The function was only temporarily deactivated to be able to continue testing with an installable version and not to lose time.

2023-09-22 09:45 UTC, MrMusic commented
The error is
`0 class_exists(): Argument #1 ($class) must be of type string, Joomla\Component\Mails\Administrator\Table\TemplateTable given `
and occurs in line 461 of script.php.
The change to `$db = Factory::getContainer()->get(DatabaseInterface::class);` has no effect here.

2023-09-23 09:39 UTC, Elfangor93 commented
>The error is `0 class_exists(): Argument #1 ($class) must be of type string, Joomla\Component\Mails\Administrator\Table\TemplateTable given` and occurs in line 461 of script.php.

Change the code to the following and the error is gone:
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/6eb4412c-ed85-4bca-bf26-cbe4d3edf018)

2023-09-25 07:36 UTC, MrMusic commented
@Elfangor93 Thank you. Error fixed.

2023-09-25 08:37 UTC, Elfangor93 commented on administrator/com_joomgallery/src/View/Control/HtmlView.php
> +  $db = Factory::getContainer()->get('DatabaseDriver');
Ja, funktionieren tut beides, zumindest bis und mit Joomla 6. Jedoch ist die Variante über das DatabaseInterface definitiv die bevorzugte Variante, da die Klassen unabhängig funktioniert. Das ist ja eben gerade der Vorteil von Interfaces...

2023-09-25 11:59 UTC, MrMusic commented
New error:
When editing an image, the following error occurs:
`0 Joomla\CMS\Form\Field\EditorField::filter field `imgtext` calls a deprecated filter class JComponentHelper, the class needs to be namespaced use \Joomla\CMS\Component\ComponentHelper instead or activate the backward compatible plugin. `

I have now changed the filter in the image, category and tag xml from
`filter="JComponentHelper::filterText"`
to
`filter="\Joomla\CMS\Component\ComponentHelper::filterText"`
I hope this is correct.

2023-09-25 13:52 UTC, Elfangor93 commented
>I have now changed the filter in the image, category and tag xml from `filter="JComponentHelper::filterText"` to
`filter="\Joomla\CMS\Component\ComponentHelper::filterText"` I hope this is correct.

Yes, this seems to be correct. At least Joomla 5 is doing the same in the core ...
![grafik](https://github.com/JoomGalleryfriends/JG4-dev/assets/39154009/0e2af95e-bc47-45fc-83d5-e10f0fe48d8f)

2023-09-25 13:53 UTC, Elfangor93 commented
>After installing the JoomGallery, the 'start' and the 'languages' buttons appear. Is the 'languages' button still necessary?

No, I dont think so. I just copied that from JG3.

2023-09-26 18:34 UTC, MrMusic commented
For testing I have adapted the Quickicon plugin for Joomla 4 and put it up as available extension for download.
In the upper area of the control panel you could remove the white background, then it looks like this:
![control-panel-transparent](https://github.com/JoomGalleryfriends/JG4-dev/assets/9802593/fdf29152-85d1-4f16-9cc9-e5f2b8d603b9)
Better or leave it white??

2023-09-27 06:21 UTC, rowi68 commented
Upper area looks better now...

2023-09-28 12:36 UTC, MrMusic commented
Instead of displaying the defined image top lists above the news area, i set now a link to the image manager.
The image manager already provides all necessary functions to sort the images by any criteria. This saves a lot of code in the HtmlView.php.
The demand number of images to be displayed is no longer necessary.
The statistic and the info area are now a bit extended.
From my side the PR is now finished.
Are there still change requests?

2023-10-11 10:20 UTC, MrMusic commented
Last change: link text to be similar to the Joomla core

2023-10-23 19:26 UTC, Elfangor93 commented on script.php
> +/* auskommentiert wegen fehler in J5
Alright, lets do that:
Add "ToDo" to the comment. This way we can find lines of code again easily, which need to be fixed or reworked before the release.

2023-10-24 09:17 UTC, MrMusic commented on script.php
> +/* auskommentiert wegen fehler in J5
>Add "ToDo" to the comment...

Yes, we can do that in the future. Here in this PR it is no longer necessary.

2023-10-30 10:27 UTC, AlexanderSupp commented
I installed this PR in my Joomla 5.0 JoomGallery 4 Test System with a concept for documentation.
http://joomgallery4.fotofreunde-much.de
Everything works fine, and the “Control Panel” looks good.
Before, I changed my Joomla 4.4 to 5.0 with a difficult process. 
The reason was, that my provider has not the recommanded database version. So I changed from MySQL to MariaDB.
See https://www.joomla.de/joomla/anforderungen

However, this PR is ready to merge into main as early as possible..
Thanks.

2023-11-07 20:21 UTC, Elfangor93 approved these changes

2023-11-07 20:21 UTC, merged