typos, spelling, grammar
JoomGalleryfriends/JG4-dev pull request #312
Opened 2024-12-27 19:15 UTC by brianteeman

non-exhaustive corrections

will make it easier for translators if the english strings are correct and understable will make it easier for developers if the english comments are correct and understandable

2024-12-29 09:53 UTC, Elfangor93 requested changes

2024-12-29 09:53 UTC, Elfangor93 commented on administrator/com_joomgallery/src/Model/CategoryModel.php
> +    // Load caegory table
I guess this here is still a typo  ;-)

2024-12-29 09:54 UTC, Elfangor93 commented
Thank you @brianteeman for your effort.
This is huge - hanving a good english speaker looking over my spelling.

2024-12-29 10:12 UTC, brianteeman commented
It is not 100% complete as there is too much code to review it all but it should cover most issues. 

Note I did not touch any code related "spelling errors"

2024-12-29 12:37 UTC, Elfangor93 approved these changes

2024-12-29 14:44 UTC, eumel1602 approved these changes
it's ok! Thanks Brian!!!

2024-12-29 14:50 UTC, merged

2024-12-31 18:11 UTC, Elfangor93 commented on administrator/com_joomgallery/src/Service/Uploader/Uploader.php
> +              $this->e
Unintentionally deleted lines of code. Will be fixed with PR #318.