Fix language files
JoomGalleryfriends/JG4-dev pull request #38
Opened 2022-09-21 12:01 UTC by MrMusic

>i tested all available screens and gave my suggestions to existing translations. They are regarding meaning, punctuation, settings path correction, form and typos.

@szepty-ziemi Thank you very much for your extensive tests and advice in https://github.com/JoomGalleryfriends/JG4-dev/pull/34

For the most part, i have adopted your suggestions. sometimes i have made some additional changes to the texts to clarify.

2022-09-25 11:24 UTC, Elfangor93 commented
I added my comments to #34...

2022-09-25 11:46 UTC, Elfangor93 requested changes
See my comments in the code...

2022-09-25 11:46 UTC, Elfangor93 commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> -COM_JOOMGALLERY_IMGDATE_DESC="Date when the picture was taken"
I chnaged this by purpose to Recording Date. Since we have now two date fields for each image in the database we can store both recording date and upload date seperately.
imgdate: Recording date
created_time: Uploading date

2022-09-25 11:46 UTC, Elfangor93 commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> -COM_JOOMGALLERY_ACTION_IMAGE_DELETE_OWN_DESC="Text to be defined..."
From my point of view this action descriptions have to be rewritten. I never understood why this is a "new setting"...

2022-09-25 11:46 UTC, Elfangor93 commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> -COM_JOOMGALLERY_SHOW_SETTINGS="Show Settings"
If you change the content of the string, please change the string accordingly...

2022-09-25 11:46 UTC, Elfangor93 commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> +COM_JOOMGALLERY_CONFIG_MAX_USERCATS_LONG="How many categories frontend user is allowed to create?"
I would prefere:
How many categories a frontend user is allowed to create?

2022-09-25 11:46 UTC, Elfangor93 commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> +COM_JOOMGALLERY_IPTC_SUBLOCATIONLEGACY="IPTC-Location"
This language strings are already definied in com_joomgallery.exif.ini and com_joomgallery.iptc.ini. No need to add them also to this file. I will ad the code to load the two missing language files in the configuration manager soon...

2022-09-25 11:46 UTC, Elfangor93 commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.sys.ini
> +COM_JOOMGALLERY_SERVICE_ERROR_COPY_IMAGETYPE="Error when copying file %s"
Maybe we should clean out this file too?
Till now it is a direct copy of JoomGallery 3...

2022-09-28 10:36 UTC, MrMusic commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> -COM_JOOMGALLERY_IMGDATE_DESC="Date when the picture was taken"
Yes, I understood that and I think it's a good thing. However, the date of recording is normally only given for photos that were taken with a camera. There is no date of recording for images taken on a computer. In addition, the 'Use image metadata' option must also be activated.
That's why I wanted to give the field a more 'general' descrition, as it doesn't always have to correspond to the date the image was taken. Furthermore, I would automatically fill the field with the upload date unless something else is set in 'Use image metadata'.

2022-09-28 10:40 UTC, MrMusic commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> -COM_JOOMGALLERY_ACTION_IMAGE_DELETE_OWN_DESC="Text to be defined..."
These texts were taken over from Joomla 3, see screenshot of Joomla categories. 
![Joomla3-category-permission](https://user-images.githubusercontent.com/9802593/192758817-4fbd1b52-e8cb-4749-b146-5ad281de724e.jpg)
But you are right, they are a bit difficult to understand. I will change it.

2022-09-28 10:41 UTC, MrMusic commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> -COM_JOOMGALLERY_SHOW_SETTINGS="Show Settings"
OK, I will change it.

2022-09-28 10:41 UTC, MrMusic commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> +COM_JOOMGALLERY_CONFIG_MAX_USERCATS_LONG="How many categories frontend user is allowed to create?"
OK, I will change it.

2022-09-28 10:42 UTC, MrMusic commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> +COM_JOOMGALLERY_IPTC_SUBLOCATIONLEGACY="IPTC-Location"
OK, after adding the code I will remove the constants from the com_joomgallery.ini again.

2022-09-28 10:42 UTC, MrMusic commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.sys.ini
> +COM_JOOMGALLERY_SERVICE_ERROR_COPY_IMAGETYPE="Error when copying file %s"
Agreed. 
I will remove all constants that are not currently used in the code.

2022-10-06 05:13 UTC, Elfangor93 commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> -COM_JOOMGALLERY_IMGDATE_DESC="Date when the picture was taken"
The field created_time will be filled anyway with the uploading date. We can create the frontedn in such a way that it uses created_time if imgdate is empty.
If we would automatically fill the field with the upload date we would have this info doubled. So no need for that...

2022-10-06 16:52 UTC, eumel1602 commented
In the options of the JoomGallery a string is wrong ?!
![1](https://user-images.githubusercontent.com/96334985/194372720-24a49a23-1397-4f96-86e9-0754865c9012.jpg)

2022-10-06 16:56 UTC, eumel1602 commented
I couldn't find any other major mistakes!
As far as I know, I have not checked spelling or grammar

Windows 10 / PHP 7.4 J4.2.3.

2022-10-07 05:50 UTC, Elfangor93 commented
> The global configuration cannot be saved for me. There is an error:
![2](https://user-images.githubusercontent.com/96334985/194373023-1cf9bca9-da2d-4fb1-9d63-162d1a0a336e.jpg)

This issue is already reported. It has nothing to do with the language
https://github.com/JoomGalleryfriends/JG4-dev/issues/40

2022-10-07 11:49 UTC, MrMusic commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> -COM_JOOMGALLERY_IMGDATE_DESC="Date when the picture was taken"
>We can design the frontend to use created_time when imgdate is empty.

Yes, that would be similar to author and owner.
Personally, I would be in favour of a clear separation of the two data fields. 
But anyway, I have now changed the description again.

2022-10-07 11:50 UTC, MrMusic commented
> In the options of the JoomGallery a string is wrong ?! ![1](https://user-images.githubusercontent.com/96334985/194372720-24a49a23-1397-4f96-86e9-0754865c9012.jpg)

Confirmed, but i don't know if this option is still needed in the future? @Elfangor93 ?

2022-10-08 11:11 UTC, Elfangor93 commented
> Confirmed, but i don't know if this option is still needed in the future? @Elfangor93 ?

I think we can remove that.

2022-10-10 12:37 UTC, Elfangor93 approved these changes

2022-10-10 12:37 UTC, Elfangor93 commented on administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
> +COM_JOOMGALLERY_CONFIG_IMAGEPROCESSOR_LONG="Choose the tool used for image processing.{tip}The tool should already be installed on the server and is required for manipulating images such as resizing
This language constant will be changed anyway in the next PR (Configuration manager).

2022-10-20 15:22 UTC, Elfangor93 commented
@MrMusic Is there still something to discuss or can we merge this PR?

2022-10-20 16:38 UTC, szepty-ziemi commented
@Elfangor93 it's ok from my side

2022-10-21 10:04 UTC, MrMusic commented
>@MrMusic Is there still something to discuss or can we merge this PR?

From my side, everything is discussed and the PR can be merged.

2022-10-22 12:57 UTC, szepty-ziemi commented
One more thing. When we click "Options" in Joomgallery we should have a meaningful title here:

![obraz](https://user-images.githubusercontent.com/60470150/197340194-ca720c8b-f6da-4902-ae55-7b364259b354.png)

2022-10-25 12:31 UTC, MrMusic commented
>One more thing. When we click "Options" in Joomgallery we should have a meaningful title here:

Should be fixed now. Thanks @szepty-ziemi

2022-10-26 10:44 UTC, MrMusic commented
Fix two problems reported here: https://github.com/JoomGalleryfriends/JG4-dev/pull/47#issuecomment-1287651861. Thanks @eumel1602

2022-10-28 15:34 UTC, MrMusic commented
If there are no change requests, i think this PR can now be merged.

2022-10-30 15:40 UTC, merged